version: "3"

services:
    app:
      build:
        context: .
      ports:
        - "8002:8000"
      volumes:
        -  ./:/app
      command: >
        sh -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
      env_file:
        - .env
      depends_on:
        - db
        - redis

    db:
      image: postgres:14-alpine
      ports:
        - "5433:5432"
      env_file:
        - .env
    redis:
      image: redis:alpine

    celery:
      build:
        context: .
      command: celery -A library_service worker -l DEBUG -P eventlet
      volumes:
        - ./:/app
      env_file:
        - .env
      depends_on:
        - redis
        - app
      restart: no

    celery-beat:
      build:
        context: .
      command: celery -A library_service beat -l DEBUG --scheduler django_celery_beat.schedulers:DatabaseScheduler
      volumes:
        - ./:/app
      env_file:
        - .env
      depends_on:
        - redis
        - app

#    flower:
#      image: mher/flower
#      ports:
#        - "5555:5555"
#      environment:
#        - CELERY_BROKER_URL=redis://redis:6379/0
#      command: celery -A library_service flower
#      depends_on:
#        - redis
#        - celery