# Generated by Django 5.0.6 on 2024-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="money_to_pay",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
