# Generated by Django 5.0.6 on 2024-06-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_alter_payment_money_to_pay"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("PN", "PENDING"), ("PD", "PAID"), ("EX", "Expired")],
                max_length=2,
            ),
        ),
    ]
