# Generated by Django 5.0.6 on 2024-06-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_payment_expires_at_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
