# Generated by Django 5.0.6 on 2024-06-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
        ("borrowing", "0004_alter_borrowing_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="book_id",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowings",
                to="book.book",
            ),
            preserve_default=False,
        ),
    ]
